# Generated by Django 3.0.6 on 2020-06-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_state',
            field=models.CharField(default='created', help_text='User state', max_length=32),
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
